"use client";

import Link from "next/link";
import { ErrorNotice, Loading, StatusPill, useAuth } from "@/components/site-shell";
import { usePolling, type Catalog } from "@/lib/client";

export default function HomePage() {
  const { user } = useAuth();
  const { data, error, loading, refresh } = usePolling<Catalog>("/catalog");
  const askHref = user?.role === "ASKER" ? "/ask" : "/login";
  const answerHref = user?.role === "ANSWERER" ? "/answer" : "/login";
  return <><section className="hero"><div><div className="eyebrow">一起把问题想明白</div><h1>卡住的那道题，<br />找一位<em>在线伙伴</em>聊聊。</h1><p>选择科目，带着一个具体问题，与成年全日制在校伙伴实时交流。按次答疑，随时可以结束。</p><div className="hero-actions"><Link href={askHref} className="button primary">我要提问 <span aria-hidden>↗</span></Link><Link href={answerHref} className="button secondary">我要答疑</Link></div></div><div className="hero-art" aria-hidden><div className="bubble-card"><strong>带着问题来</strong>一道题、一个概念，或一段没想通的推导。<br /><small>把具体疑惑描述清楚</small></div><div className="bubble-card"><strong>带着思路走</strong>真人实时交流，理清步骤，一起找到下一步。<br /><small>一次问题 · 一次答疑</small></div></div></section><ErrorNotice error={error} retry={() => void refresh()} /><section><div className="section-title"><div><h2>从一个科目开始</h2><p>选择你正在备考的方向</p></div></div>{loading && !data ? <Loading text="正在读取科目与在线状态…" /> : <div className="subject-grid">{data?.subjects.map((subject, i) => <Link key={subject.id} href={`${askHref}${askHref === "/ask" ? `?subject=${subject.id}` : ""}`} className="subject-card"><span className="subject-icon" aria-hidden>{["∑", "Aa", "文", "⌘"][i % 4]}</span><div><strong>{subject.name}</strong><small>具体问题，即时交流</small></div></Link>)}</div>}</section><section><div className="section-title"><div><h2>在线答疑伙伴</h2><p>测试资料 · 全日制在校大学生或研究生，成年且非在职</p></div><span className="section-count">{data?.onlineCount ?? 0} 人在线</span></div>{data && data.onlineCount === 0 && <div className="notice">暂时没有可接单的在线答疑者。你可以发起快速匹配等待，也可以在另一独立浏览器会话中登录答疑者并主动上线。</div>}<div className="answerer-grid">{data?.answerers.map(answerer => <article className="card answerer-card" key={answerer.id}><div className="answerer-top"><div className="avatar">{answerer.name.slice(-1)}</div><div className="answerer-name"><h3>{answerer.name}</h3><small>虚构演示资料</small></div><StatusPill status={answerer.status} /></div><div className="tags">{answerer.subjects.map(subject => <span className="tag" key={subject.id}>{subject.name}</span>)}</div><p className="bio">{answerer.bio || "带着具体问题来，一起理清思路。"}</p>{answerer.status === "AVAILABLE" && answerer.enabled ? <Link className="button secondary" href={askHref === "/ask" ? `/ask?answerer=${answerer.id}` : askHref}>向这位伙伴提问 <span aria-hidden>↗</span></Link> : <button className="button secondary" disabled>{answerer.status === "BUSY" ? "正在答疑中" : "暂时离线"}</button>}</article>)}</div></section><div className="how-row">{[["01", "描述一个具体问题", "选择科目，补充你的卡点与尝试。"], ["02", "等在线伙伴接受", "指定一位伙伴，或进行快速匹配。"], ["03", "进入临时答疑室", "实时文字交流，结束后留下反馈。"]].map(([num, title, description]) => <div className="how-item" key={num}><span className="how-num">{num}</span><div><strong>{title}</strong><p>{description}</p></div></div>)}</div></>;
}
