"use client";

import Link from "next/link";
import { AuthGate, Empty, ErrorNotice, Loading, PageHeading, StatusPill, useAuth } from "@/components/site-shell";
import { usePolling, type Catalog } from "@/lib/client";

export default function StudentPage() { return <AuthGate role="ASKER"><StudentHome /></AuthGate>; }

function StudentHome() {
  const { user } = useAuth();
  const { data, error, loading, refresh } = usePolling<Catalog>("/catalog");
  return <><PageHeading eyebrow="学生中心" title={`${user?.name || "同学"}，今天想理清哪个问题？`} description="选择一个科目，描述你的具体疑问，与在线教师开始一次实时交流。" action={<Link className="button primary" href="/student/ask">发起提问 ↗</Link>} /><ErrorNotice error={error} retry={() => void refresh()} /><section><div className="section-title"><div><h2>从一个科目开始</h2><p>聚焦一道题、一个概念，或一个推导步骤。</p></div></div>{loading && !data ? <Loading text="正在读取科目与在线状态…" /> : <div className="subject-grid">{data?.subjects.map((subject, index) => <Link key={subject.id} href={`/student/ask?subject=${encodeURIComponent(subject.id)}`} className="subject-card"><span className="subject-icon" aria-hidden>{["∑", "Aa", "文", "⌘"][index % 4]}</span><div><strong>{subject.name}</strong><small>具体问题，即时交流</small></div></Link>)}</div>}</section><section><div className="section-title"><div><h2>选择答疑教师</h2><p>教师为成年、非在职的全日制在校大学生或研究生。</p></div><span className="section-count">{data?.onlineCount ?? 0} 人在线</span></div>{data && data.onlineCount === 0 && <div className="notice">暂时没有可接单的在线教师。你可以发起快速匹配等待，或稍后回来。</div>}{data && data.answerers.length === 0 ? <Empty title="暂时没有可展示的教师" text="科目入口仍可使用；新的在线教师加入后会出现在这里。" action={<Link className="button secondary" href="/student/ask">发起快速匹配</Link>} /> : <div className="answerer-grid">{data?.answerers.map(teacher => <article className="card answerer-card" key={teacher.id}><div className="answerer-top"><div className="avatar">{teacher.name.slice(-1)}</div><div className="answerer-name"><h3>{teacher.name}</h3><small>资料由本人填写</small></div><StatusPill status={teacher.status} /></div><div className="tags">{teacher.subjects.map(subject => <span className="tag" key={subject.id}>{subject.name}</span>)}</div><p className="bio">{teacher.bio || "带着具体问题来，一起理清思路。"}</p>{teacher.status === "AVAILABLE" && teacher.enabled ? <Link className="button secondary" href={`/student/ask?answerer=${encodeURIComponent(teacher.id)}`}>向这位教师提问 ↗</Link> : <button className="button secondary" disabled>{teacher.status === "BUSY" ? "正在答疑中" : "暂时离线"}</button>}</article>)}</div>}</section><div className="how-row">{[["01", "描述一个具体问题", "写清楚题目、尝试与疑惑。"], ["02", "等待教师接受", "指定教师，或快速匹配。"], ["03", "进入临时答疑室", "实时交流，结束后留下反馈。"]].map(([number, title, description]) => <div className="how-item" key={number}><span className="how-num">{number}</span><div><strong>{title}</strong><p>{description}</p></div></div>)}</div></>;
}
